# This is a basic workflow to help you get started with Actions

name: Test and Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # branches: [ "main", "develop", "release/**", "feature/**", "hotfix/**" ]
      branches: [ "main"]
  pull_request:
    branches: [ develop ]

jobs:
  unitTests:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3      
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester Unit.Tests.ps1 -Passthru
  publish:
      needs: unitTests        
      - name: Publish with powershell
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          API_KEY: ${{ secrets.Powershell_Gallery_Api_Key }}
        run: |
          $m = Find-Module 'ElCocktail'
          $versionMajor = 1
          $version = "$($versionMajor).$($m.version.minor+1).0.0"
          write-host publishing version $version
          #.\publish.ps1 -version $version apiKey $env:API_KEY
