# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # branches: [ "main", "develop", "release/**", "feature/**", "hotfix/**" ]
      branches: [ "main"]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs 
      - name: Publish with powershell
        env:
          API_KEY: ${{ secrets.Powershell_Gallery_Api_Key }}
        run: |
          $m = Find-Module 'ElCocktail'
          $version = "$($m.version.major).$($m.version.minor+1).0.0"
          write-host m - $m
          write-host version $m.version
          write-host version major $m.version[0]
          write-host "Calculated version is :" $version
          #.\publish.ps1 -version 1.0.0.2 apiKey $env:API_KEY
