name: TestAndPublish

on:
  push:
    # branches: [ "main", "develop", "release/**", "feature/**", "hotfix/**" ]
      branches: [ "main"]
  pull_request:
    branches: [ develop ]

jobs:
  Unit-Tests:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3      
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester Unit.Tests.ps1 -Passthru
  
  Publish:
    needs: Unit-Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish with powershell
        env:
          API_KEY: ${{ secrets.Powershell_Gallery_Api_Key }}
        run: |
          $m = Find-Module 'ElCocktail'
          $version = "$($m.version.major).$($m.version.minor+1).0.0"
          write-host "Calculated version is :" $version
          .\publish.ps1 -version 1.0.0. apiKey $env:API_KEY
